-- ½ÃÄö½º »ý¼º

CREATE SEQUENCE product_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE event_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE coupon_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE order_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE product_bbs_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE customer_bbs_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE delivery_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE cart_id_seq START WITH 1 INCREMENT BY 1 NOCYCLE;

DROP SEQUENCE product_id_seq;

DROP SEQUENCE cart_count_seq;